version: "2"
plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  gnu-complexity:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true